spring:
  datasource:
    url: jdbc:mysql://192.168.10.254:3306/dkm_game?useUnicode=&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: kgdatj1110
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 192.168.10.254
    username: guest
    password: guest
    port: 5672
    virtual-host: /
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
  redis:
    host: 192.168.10.254
    timeout: 2000
    jedis:
      pool:
        max-wait: 1000
        max-active: 20
        min-idle: 1

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://192.168.10.254:10000/eureka

feign:
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 10000

hystrix:
  metrics:
    enabled: true
    polling-interval-ms: 4000
